In [313]:
import pandas as pd

In [314]:
consump = pd.read_excel("consumption.xlsx",engine='openpyxl')

In [315]:
consump

,อาหารญี่ปุ่น,อาหารจึน,อาหารไทย,อาหารอีสาน,อาหารสุขภาพ,บุฟเฟต์,ชาบูชาบู,ปิ้งย่าง,เหล้าเบียร์,เสื้อผ้าแฟชั่น,...,Content เกี่่ยวกับเกมส์,Content เกี่ยวกับการ review ร้านอาหาร,Content เกี่ยวกับการท่องเที่ยว,Content เกี่ยวกับการแต่งบ้าน,Content เกี่ยวกับการโทรทัศน์,Content เกี่ยวกับละคร,Content เกี่ยวกับการเมือง,Other_comment,อายุ,เพศ
0,2,1,5,4,5,2,2,3,4,1,...,3,2,2,2,2,2,5,"กีฬา UFC, Soccer",33,ชาย
1,4,1,5,4,4,2,2,2,0,3,...,2,5,5,4,1,1,4,กีฬา สัตว์เลี้ยง เทคโนโลยี,28,หญิง
2,4,1,5,1,1,3,3,3,0,0,...,5,5,2,2,2,1,5,-,28,ชาย
3,3,0,5,2,0,3,3,3,0,0,...,5,3,3,0,0,0,2,"โหราศาสตร์,ดูดวง",27,ชาย
4,2,3,4,4,5,1,1,1,3,3,...,0,3,2,3,0,0,2,สัตว์เลี้ยง,26,หญิง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,1,1,5,2,1,1,1,1,1,1,...,0,3,1,1,5,5,4,เรื่องเกี่ยวกับ ตลกขบขัน และ ธรรมะ,48,หญิง
59,1,1,5,2,2,2,2,3,1,1,...,2,1,3,0,0,1,4,Podcast การพัมนาตนเอง,32,ชาย
60,3,1,5,4,4,1,1,3,1,2,...,4,5,5,2,3,3,2,Content เกี่ยวกับสัตว์เลี้ยง,27,หญิง
61,2,1,2,4,3,3,3,3,1,1,...,3,3,2,2,0,1,1,ซีรี่ส์เกาหลี อาหารเกาหลี,31,หญิง
62,2,3,5,4,5,3,3,3,1,0,...,2,3,3,3,1,1,1,การลงทุน,30,ไม่ต้องการระบุ

In [328]:
consump.columns

Index(['อาหารญี่ปุ่น', 'อาหารจึน', 'อาหารไทย', 'อาหารอีสาน', 'อาหารสุขภาพ',
       'บุฟเฟต์', 'ชาบูชาบู', 'ปิ้งย่าง', 'เหล้าเบียร์', 'เสื้อผ้าแฟชั่น',
       'แต่งหน้า', 'skincare บำรุงผิว', 'การออกกำลังกาย', 'การเล่นเกมส์',
       'การท่องเที่ยว', 'การอ่านหนังสือ', 'การอ่านบทความ Online',
       'การเรียน e-learning', 'ดู Series', 'ดูหนัง', 'ดู Youtube',
       'ดู Netflix', 'Content ด้านบันเทิง', 'Content เกี่่ยวกับเกมส์',
       'Content เกี่ยวกับการ review ร้านอาหาร',
       'Content เกี่ยวกับการท่องเที่ยว', 'Content เกี่ยวกับการแต่งบ้าน',
       'Content เกี่ยวกับการโทรทัศน์', 'Content เกี่ยวกับละคร',
       'Content เกี่ยวกับการเมือง', 'Other_comment', 'อายุ', 'เพศ'],
      dtype='object')

In [329]:
col_name = ['อาหารญี่ปุ่น', 'อาหารจึน', 'อาหารไทย', 'อาหารอีสาน', 'อาหารสุขภาพ',
       'บุฟเฟต์', 'ชาบูชาบู', 'ปิ้งย่าง', 'เหล้าเบียร์', 'เสื้อผ้าแฟชั่น',
       'แต่งหน้า', 'skincare บำรุงผิว', 'การออกกำลังกาย', 'การเล่นเกมส์',
       'การท่องเที่ยว', 'การอ่านหนังสือ', 'การอ่านบทความ Online',
       'การเรียน e-learning', 'ดู Series', 'ดูหนัง', 'ดู Youtube',
       'ดู Netflix', 'Content ด้านบันเทิง', 'Content เกี่่ยวกับเกมส์',
       'Content เกี่ยวกับการ review ร้านอาหาร',
       'Content เกี่ยวกับการท่องเที่ยว', 'Content เกี่ยวกับการแต่งบ้าน',
       'Content เกี่ยวกับการโทรทัศน์', 'Content เกี่ยวกับละคร',
       'Content เกี่ยวกับการเมือง']

In [334]:
cn = 0
score = []
cat_add = []
ID = []
Type = []
comment = []
for i in col_name:
    val = consump[[i]].values.T.ravel().tolist()
    for q in val:
        score.append(q)
    for k in range(1,64):
        ID.append(k)
    for j in range(1,64) :
        cat_add.append("บริโภค"+i)
    for p in range(1,64):
        Type.append("Consumption")
    val2 = consump[["Other_comment"]].values.T.ravel().tolist()
    for o in val2:
        comment.append(o)

In [335]:
df = pd.DataFrame(list(zip(cat_add,score,ID,comment,Type)), columns= [["Category","Score","ID","Comment","Type"]])

In [336]:
df.to_excel("data_consumption.xlsx")

In [298]:
df

,Category,Score,ID,Comment,Type
0,อาหารญี่ปุ่น,2,1,"กีฬา UFC, Soccer",Consumption
1,อาหารญี่ปุ่น,4,2,กีฬา สัตว์เลี้ยง เทคโนโลยี,Consumption
2,อาหารญี่ปุ่น,4,3,-,Consumption
3,อาหารญี่ปุ่น,3,4,"โหราศาสตร์,ดูดวง",Consumption
4,อาหารญี่ปุ่น,2,5,สัตว์เลี้ยง,Consumption
...,...,...,...,...,...
1885,Content เกี่ยวกับการเมือง,4,59,เรื่องเกี่ยวกับ ตลกขบขัน และ ธรรมะ,Consumption
1886,Content เกี่ยวกับการเมือง,4,60,Podcast การพัมนาตนเอง,Consumption
1887,Content เกี่ยวกับการเมือง,2,61,Content เกี่ยวกับสัตว์เลี้ยง,Consumption
1888,Content เกี่ยวกับการเมือง,1,62,ซีรี่ส์เกาหลี อาหารเกาหลี,Consumption
1889,Content เกี่ยวกับการเมือง,1,63,การลงทุน,Consumption

In [338]:
interest = pd.read_excel("interest.xlsx",engine='openpyxl')

In [339]:
interest.head()

,อาหารญี่ปุ่น,อาหารจึน,อาหารไทย,อาหารอีสาน,อาหารสุขภาพ,บุฟเฟต์,ชาบูชาบู,ปิ้งย่าง,เหล้าเบียร์,เสื้อผ้าแฟชั่น,...,Content เกี่่ยวกับเกมส์,Content เกี่ยวกับการ review ร้านอาหาร,Content เกี่ยวกับการท่องเที่ยว,Content เกี่ยวกับการแต่งบ้าน,Content เกี่ยวกับการโทรทัศน์,Content เกี่ยวกับละคร,Content เกี่ยวกับการเมือง,Other_comment,อายุ,เพศ
0,4,4,6,5,4,4,4,4,6,3,...,5,5,3,3,3,3,6,"กีฬา UFC, Soccer",33,ชาย
1,5,3,6,5,4,5,6,5,2,3,...,3,5,6,6,3,2,4,กีฬา สัตว์เลี้ยง เทคโนโลยี,28,หญิง
2,6,3,5,4,3,6,6,6,1,3,...,6,6,6,6,5,2,6,-,28,ชาย
3,4,3,3,3,4,4,4,4,0,0,...,6,3,4,3,2,0,5,"โหราศาสตร์,ดูดวง",27,ชาย
4,5,4,4,4,6,3,3,3,3,3,...,2,3,4,4,2,2,3,สัตว์เลี้ยง,26,หญิง

In [340]:
interest.columns

Index(['อาหารญี่ปุ่น', 'อาหารจึน', 'อาหารไทย', 'อาหารอีสาน', 'อาหารสุขภาพ',
       'บุฟเฟต์', 'ชาบูชาบู', 'ปิ้งย่าง', 'เหล้าเบียร์', 'เสื้อผ้าแฟชั่น',
       'แต่งหน้า', 'skincare บำรุงผิว', 'การออกกำลังกาย', 'การเล่นเกมส์',
       'การท่องเที่ยว', 'การอ่านหนังสือ', 'การอ่านบทความ Online',
       'การเรียน e-learning', 'ดู Series', 'ดูหนัง', 'ดู Youtube',
       'ดู Netflix', 'Content ด้านบันเทิง', 'Content เกี่่ยวกับเกมส์',
       'Content เกี่ยวกับการ review ร้านอาหาร',
       'Content เกี่ยวกับการท่องเที่ยว', 'Content เกี่ยวกับการแต่งบ้าน',
       'Content เกี่ยวกับการโทรทัศน์', 'Content เกี่ยวกับละคร',
       'Content เกี่ยวกับการเมือง', 'Other_comment', 'อายุ', 'เพศ'],
      dtype='object')

In [341]:
col = ['อาหารญี่ปุ่น', 'อาหารจึน', 'อาหารไทย', 'อาหารอีสาน', 'อาหารสุขภาพ',
       'บุฟเฟต์', 'ชาบูชาบู', 'ปิ้งย่าง', 'เหล้าเบียร์', 'เสื้อผ้าแฟชั่น',
       'แต่งหน้า', 'skincare บำรุงผิว', 'การออกกำลังกาย', 'การเล่นเกมส์',
       'การท่องเที่ยว', 'การอ่านหนังสือ', 'การอ่านบทความ Online',
       'การเรียน e-learning', 'ดู Series', 'ดูหนัง', 'ดู Youtube',
       'ดู Netflix', 'Content ด้านบันเทิง', 'Content เกี่่ยวกับเกมส์',
       'Content เกี่ยวกับการ review ร้านอาหาร',
       'Content เกี่ยวกับการท่องเที่ยว', 'Content เกี่ยวกับการแต่งบ้าน',
       'Content เกี่ยวกับการโทรทัศน์', 'Content เกี่ยวกับละคร',
       'Content เกี่ยวกับการเมือง']

In [342]:
cn = 0
score = []
cat_add = []
ID = []
Type = []
comment = []
for i in col:
    val = consump[[i]].values.T.ravel().tolist()
    for q in val:
        score.append(q)
    for k in range(1,64):
        ID.append(k)
    for j in range(1,64) :
        cat_add.append("สนใจ"+i)
    for p in range(1,64):
        Type.append("Interest")
    val2 = consump[["Other_comment"]].values.T.ravel().tolist()
    for o in val2:
        comment.append(o)

In [343]:
df = pd.DataFrame(list(zip(cat_add,score,ID,comment,Type)), columns= [["Category","Score","ID","Comment","Type"]])

In [344]:
df.to_excel("data_interest.xlsx")

In [345]:
df

,Category,Score,ID,Comment,Type
0,สนใจอาหารญี่ปุ่น,2,1,"กีฬา UFC, Soccer",Interest
1,สนใจอาหารญี่ปุ่น,4,2,กีฬา สัตว์เลี้ยง เทคโนโลยี,Interest
2,สนใจอาหารญี่ปุ่น,4,3,-,Interest
3,สนใจอาหารญี่ปุ่น,3,4,"โหราศาสตร์,ดูดวง",Interest
4,สนใจอาหารญี่ปุ่น,2,5,สัตว์เลี้ยง,Interest
...,...,...,...,...,...
1885,สนใจContent เกี่ยวกับการเมือง,4,59,เรื่องเกี่ยวกับ ตลกขบขัน และ ธรรมะ,Interest
1886,สนใจContent เกี่ยวกับการเมือง,4,60,Podcast การพัมนาตนเอง,Interest
1887,สนใจContent เกี่ยวกับการเมือง,2,61,Content เกี่ยวกับสัตว์เลี้ยง,Interest
1888,สนใจContent เกี่ยวกับการเมือง,1,62,ซีรี่ส์เกาหลี อาหารเกาหลี,Interest
1889,สนใจContent เกี่ยวกับการเมือง,1,63,การลงทุน,Interest